@ISPT_Project_Backend.Server_HostAddress = http://localhost:5293

GET {{ISPT_Project_Backend.Server_HostAddress}}/weatherforecast/
Accept: application/json

### Obtener todas las carreras
GET {{ISPT_Project_Backend.Server_HostAddress}}/api/careers
Accept: application/json

###


### Crear carrera
POST {{ISPT_Project_Backend.Server_HostAddress}}/api/careers
Content-Type: application/json

{
    "name": "Ingeniería en Sistemas",
    "title": "Ingeniero"
}

###

### Modificar carrera
PUT {{ISPT_Project_Backend.Server_HostAddress}}/api/careers/1
Content-Type: application/json

{
    "id": 1,
    "name": "dfhfd",
    "title": "sdg"
}

###
POST {{ISPT_Project_Backend.Server_HostAddress}}/api-v1/auth/login
Content-Type: application/json
{
    "Username": "SuperadminISPT-2026",
    "Password": "!ISPT-AQUILES-#2026#",
    "RememberMe": true
}

###
POST {{ISPT_Project_Backend.Server_HostAddress}}/api-v1/auth/refresh
Content-Type: application/json
{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6InN1cGVyYWRtaW5JU1BULTIwMjYiLCJVc2VybmFtZSI6IlN1cGVyYWRtaW5JU1BULTIwMjYiLCJqdGkiOiIyYjIyYmNhMS0wZDVjLTRjNGItOGZmZi1iOTVkZDVlOWNjOWEiLCJSb2xlIjoiRGlyZWN0aXZvIiwiZXhwIjoxNzgxMDA3OTc1LCJpc3MiOiJBYnJlZ3UmU29icmVybzIwMjYtSVNQVCIsImF1ZCI6IlBFUEVDIy5ORVQxMCJ9.q9S16s4sX60rdbpp1VyDhIF1NRHIV1vUhqo_MpJdDcg",
    "refreshToken": "TJ7iH3eaLMGQk+n78ekjRMVXd4+fmbN9Lny8VILuq8rzx/4jJursHFAwn6Cqt5spabRU7PJUAgcPXZINnmS/Tg==",
    "expiresIn": 900
}